// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCustomDir(arg1:string):Promise<void>;

export function AddExcludeDir(arg1:string):Promise<void>;

export function AnalyzeComponentStore():Promise<string>;

export function ApplyUpdateAndRestart():Promise<string>;

export function CheckUpdate(arg1:boolean):Promise<main.UpdateInfoDTO>;

export function CleanRegistry(arg1:Array<string>):Promise<main.CleanResult>;

export function CleanSelected(arg1:Array<string>):Promise<main.CleanResult>;

export function ClearUpdateSkip():Promise<void>;

export function FindLockers(arg1:Array<string>):Promise<Array<main.LockerDTO>>;

export function GetCustomDirs():Promise<Array<string>>;

export function GetDismInfo():Promise<main.DismInfoDTO>;

export function GetExcludeDirs():Promise<Array<string>>;

export function GetHistory():Promise<Array<main.HistoryDTO>>;

export function GetUpdateDownload():Promise<main.UpdateDownloadDTO>;

export function GetVersion():Promise<string>;

export function KillProcess(arg1:Array<string>,arg2:number):Promise<string>;

export function LogFrontend(arg1:string):Promise<void>;

export function OpenDownloadPage(arg1:string):Promise<void>;

export function RemoveCustomDir(arg1:string):Promise<void>;

export function RemoveExcludeDir(arg1:string):Promise<void>;

export function Scan(arg1:string):Promise<void>;

export function ScanRegistry():Promise<Array<main.RegEntryDTO>>;

export function SkipUpdate(arg1:string):Promise<void>;

export function SnoozeUpdate(arg1:number):Promise<void>;

export function StartComponentCleanup():Promise<string>;

export function StartComponentRepair():Promise<string>;

export function StartUpdateDownload():Promise<string>;
