// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomDir(arg1) {
  return window['go']['main']['App']['AddCustomDir'](arg1);
}

export function AddExcludeDir(arg1) {
  return window['go']['main']['App']['AddExcludeDir'](arg1);
}

export function CleanRegistry(arg1) {
  return window['go']['main']['App']['CleanRegistry'](arg1);
}

export function CleanSelected(arg1) {
  return window['go']['main']['App']['CleanSelected'](arg1);
}

export function GetCustomDirs() {
  return window['go']['main']['App']['GetCustomDirs']();
}

export function GetExcludeDirs() {
  return window['go']['main']['App']['GetExcludeDirs']();
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function RemoveCustomDir(arg1) {
  return window['go']['main']['App']['RemoveCustomDir'](arg1);
}

export function RemoveExcludeDir(arg1) {
  return window['go']['main']['App']['RemoveExcludeDir'](arg1);
}

export function Scan(arg1) {
  return window['go']['main']['App']['Scan'](arg1);
}

export function ScanRegistry() {
  return window['go']['main']['App']['ScanRegistry']();
}
