// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCustomDir(arg1:string):Promise<void>;

export function AddExcludeDir(arg1:string):Promise<void>;

export function CleanRegistry(arg1:Array<string>):Promise<main.CleanResult>;

export function CleanSelected(arg1:Array<string>):Promise<main.CleanResult>;

export function GetCustomDirs():Promise<Array<string>>;

export function GetExcludeDirs():Promise<Array<string>>;

export function GetHistory():Promise<Array<main.HistoryDTO>>;

export function RemoveCustomDir(arg1:string):Promise<void>;

export function RemoveExcludeDir(arg1:string):Promise<void>;

export function Scan(arg1:string):Promise<void>;

export function ScanRegistry():Promise<Array<main.RegEntryDTO>>;
